import fs from 'node:fs';
const d=JSON.parse(fs.readFileSync('docs/content.json','utf8'));
const e=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const img=(src,alt,cls='')=>`<img src="${e(src)}" alt="${e(alt)}" class="${cls}" loading="lazy" decoding="async">`;
const hist=n=>`illustrations/${n}.webp`;
const photos={moremargin:[6],funtown:[16],bigbox:[19],campingworld:[34],lemonis:[43],courageb:[60]};
const caps={moremargin:['DJI Fifth Avenue','DJI retail display','DJI store interior','NuvoMed product'],funtown:['Fun Town RV retail','Store and showroom','Product merchandising','Parts and accessories'],bigbox:['FitBox concept rendering','FitBox concept rendering','FitBox exterior concept','FitBox interior concept'],campingworld:['Gander Outdoors','Retail merchandising','Gander Outdoors opening','RV showroom'],lemonis:['W82 · Editorial illustration','Retail concept','W82, Chicago','Retail concept'],courageb:['COURAGE. b storefront','Boutique interior','Fabric sourcing','Denim & Soul']};
const role=(r,i)=>`<details class="role" id="role-${r.id}" ${i===0?'open':''}>
 <summary><span class="role-year">${e(r.years)}</span><span class="role-title"><strong>${e(r.company)}</strong><span>${e(r.role)} · ${e(r.location)}</span></span><span class="disclosure" aria-hidden="true"></span></summary>
 <div class="role-body"><p class="role-context">${e(r.context)}</p><div class="career-story">${r.chapters.map((c,j)=>`<article><span class="eyebrow">${e(c.k)}</span><p>${e(c.text)}</p></article>`).join('')}</div>
 ${photos[r.id]?`<div class="career-photos">${photos[r.id].map((n,j)=>`<figure>${img(hist(n),caps[r.id][j])}<figcaption>${e(caps[r.id][j])} · Illustration</figcaption></figure>`).join('')}</div>`:''}
 ${r.clients?`<div class="client-work"><h4>More of the work</h4><p>${e(r.clientsIntro)}</p><div class="client-grid">${r.clients.map(c=>`<article><h5>${e(c.name)}</h5><span class="meta">${e(c.kind)}</span><p>${e(c.did)}</p></article>`).join('')}</div></div>`:''}
 <details class="small-detail"><summary>About ${e(r.company)}</summary><p>${e(r.about)}</p></details></div></details>`;
const asset=src=>{
 if(fs.existsSync('docs/'+src))return src;
 const name=src.split('/').pop()||'';
 if(/atomiq|ATOMIQ|ChatGPT/i.test(src)){
  if(/mobile/i.test(name))return 'uploads/atomiq-mobile.png';
  if(/sampler/i.test(name))return 'uploads/atomiq-sampler.png';
  if(/sequencer/i.test(name))return 'uploads/atomiq-sequencer.png';
  return 'uploads/atomiq-performance-core.png';
 }
 return null;
};
const software=p=>{
 const shots=(p.shots||[]).map(s=>({...s,src:asset(s.src)})).filter(s=>s.src);
 return `<article class="software-project" id="project-${p.id}"><div class="project-heading"><div><span class="eyebrow">${e(p.role)}</span><h3>${e(p.name)}</h3></div><span class="status">${e(p.status)}</span></div>
 <div class="project-grid"><div class="project-gallery" data-gallery>${shots.length?`<figure><a class="image-link" href="${e(shots[0].src)}" target="_blank" rel="noopener" aria-label="Open ${e(p.name)} screenshot at full size">${img(shots[0].src,shots[0].alt)}</a><figcaption>${e(shots[0].alt)}</figcaption></figure><div class="gallery-controls" role="group" aria-label="${e(p.name)} screenshots">${shots.map((s,i)=>`<button type="button" data-shot="${e(s.src)}" data-alt="${e(s.alt)}" aria-pressed="${i===0}">${e(s.lab)}</button>`).join('')}</div>`:''}</div><div class="project-copy"><ul>${(p.bullets||[]).map(b=>`<li>${e(b)}</li>`).join('')}</ul><details class="small-detail"><summary>How it comes together</summary><ol class="process-list">${(p.flow||[]).map(f=>`<li><strong>${e(f.name||f)}</strong>${f.desc?`<p>${e(f.desc)}</p>`:''}</li>`).join('')}</ol>${p.domains?`<p>${p.domains.map(e).join(' · ')}</p>`:''}<p class="meta">${e(p.label)}</p></details></div></div></article>`;
};
const pl=d.rolesData.find(r=>r.id==='campingworld');
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark light"><title>Nicolas Goureau — Retail, Consumer & Software</title><meta name="description" content="Nicolas Goureau. More than 30 years across retail, sourcing, brands, stores, and the P&L. Curious about people, products, and how things work."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;650;700;750;800&family=Source+Sans+3:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="site.css"><script src="site.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="wordmark" href="#profile" aria-label="Nicolas Goureau, introduction">Nicolas<br>Goureau<span>.</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation"><a href="#about">About</a><a href="#build">The work</a><a href="#value">Results</a><a href="#experience">Experience</a><a href="#ai">Software</a><a class="button small" href="#contact">Let’s talk</a></nav></header>
<main id="main">
<section class="hero" id="profile" aria-labelledby="hero-heading"><div class="hero-background" data-parallax="0.12"><img src="illustrations/43.webp" alt="" fetchpriority="high"></div><div class="hero-shade"></div><div class="hero-content"><p class="eyebrow">Nicolas Goureau · ATLANTA, GA</p><h1 id="hero-heading">I see possibilities.<br><span>I like figuring out</span><br>how to get there.</h1><p class="hero-lead">Give me a business problem and I’m curious—about the product, the numbers, and the people who know the business.</p><a href="#build" class="text-link">Explore the work</a><p class="availability">Open to remote or hybrid work<br>Willing to travel</p></div><div class="portrait-wrap" data-parallax="0.055"><img src="assets/img-00-tight.png" alt="Nicolas Goureau" class="portrait" fetchpriority="high"></div><div class="hero-footer"><span>Retail. Products. Brands. Stores. Software.</span><span class="location-credit">Illustrated from the work</span></div></section>
<section class="about-section" id="about"><div class="about-image"><img src="illustrations/57.webp" alt="Fabric rolls from the COURAGE. b sourcing archive" loading="lazy" data-parallax="0.04"><div class="image-note">A working life that started at twelve.</div><span class="photo-credit">COURAGE. b · Fabric sourcing</span></div><div class="about-copy"><span class="eyebrow">About me</span><h2>A little about me.</h2><p>I started working at twelve in my mother’s clothing store, steaming, folding, and tagging merchandise. Other jobs followed through high school and college. Retail was part of my life long before it became my career.</p><p>I’m American, French, and Israeli, based in Atlanta. I grew up across three cultures and have spent decades traveling through Europe, Asia, and South America. I like finding things—a supplier, a product, a deal, or an answer buried in the numbers—and I tend to stay with a question until I understand it.</p><p>For a decade, I founded and ran a fashion company alongside full-time executive roles, working nights and weekends. These days, that curiosity also takes me into building software with AI.</p><p>Outside work, there’s family, cooking, and usually something to fix. I never hire a handyman—I enjoy figuring out what’s wrong, learning how it works, and getting it working again.</p><div class="personal-notes"><p><strong>Languages</strong>English & French · Fluent<br>Hebrew · Conversational<br>Spanish · Basic</p><p><strong>Off the clock</strong>Family, cooking, art, fixing things.<br>Golf, pickleball, exploring.<br>Time with friends.</p></div></div></section>
<section class="introduction shell" aria-label="How I work"><span class="eyebrow">A question is a good place to start.</span><div><p class="intro-large">I ask questions, connect the pieces, and find ways forward.</p><p>I enjoy showing people what could work and working alongside them to make it happen. I bring 30+ years across retail, sourcing, brands, stores, and the P&amp;L. I also build software, which gives me another way to solve a problem and keep things moving.</p></div></section>
<section class="work-section light" id="build"><div class="shell"><div class="section-heading"><span class="eyebrow">What I work on</span><h2>The work usually<br>crosses departments.</h2><p>A product decision affects sourcing, pricing, stock, and what happens in the store. That’s where my experience comes together. I work through those connections with the people responsible, from the first idea to the daily work of running it.</p></div><div class="work-grid">${d.tracksData.map((t,i)=>`<article><span class="index">0${i+1}</span><h3>${e(t.name)}</h3><p>${e(t.how)}</p><details class="small-detail"><summary>Examples from the work</summary><ul class="proof-list">${t.proof.map(p=>`<li><strong>${e(p.num)}</strong><span>${e(p.what)}<small>${e(p.where)}</small></span></li>`).join('')}</ul></details></article>`).join('')}</div>
<details class="topics-section"><summary>How I approach the work <span>23 topics</span></summary><div class="topics-grid">${d.compGroupsData.map(g=>`<div><h3>${e(g.label)}</h3>${g.items.map(i=>`<details class="topic"><summary>${e(i.name)}</summary><p>${e(i.story)}</p></details>`).join('')}</div>`).join('')}</div></details></div></section>
<section class="results-section shell" id="value"><div class="section-heading"><span class="eyebrow">Results</span><h2>Here’s what that<br>work has led to.</h2></div><div class="results-grid">${d.highlightsData.map(h=>`<article><p class="result-number">${e(h.num)}<span>${e(h.unit)}</span></p><p>${e(h.desc)}</p></article>`).join('')}</div></section>
<section class="brand-story"><div class="brand-intro shell"><div><span class="eyebrow">A closer look · Private label</span><h2>From a gap on the shelf<br>to a product in hand.</h2><p>Each brand started with a question about the assortment: what was missing, and could we offer something better? The answer had to work all the way from product and packaging through sourcing, delivery, and the sale.</p></div><figure>${img('assets/cwpl-nepallo-rack.png','Nepallo fishing apparel collection')}<figcaption>Nepallo · Fishing and sun protection</figcaption></figure></div><div class="product-strip shell">${d.plWallData.slice(0,6).map(p=>`<figure>${img(p.src,p.name+' — '+p.cat)}<figcaption><strong>${e(p.name)}</strong>${e(p.cat)}</figcaption></figure>`).join('')}</div><div class="shell"><details class="small-detail private-label"><summary>Follow the product from idea to sale</summary><ol class="process-list">${d.plFlowData.map(f=>`<li><strong>${e(f.t)}</strong><p>${e(f.d)}</p></li>`).join('')}</ol>${pl.plStory.map(s=>`<article><h3>${e(s.t)}</h3><p>${e(s.d)}</p><div class="product-detail-images">${s.imgs.map(i=>img(i.src,i.alt)).join('')}</div><p class="meta">${e(s.brands)}</p></article>`).join('')}<div class="client-grid">${pl.plCats.map(c=>`<article><h4>${e(c.t)}</h4><p>${e(c.d)}</p><p class="meta">Benchmarked against ${e(c.vs)}</p></article>`).join('')}</div></details></div></section>
<section class="experience-section shell" id="experience"><div class="section-heading"><span class="eyebrow">Where I’ve worked</span><h2>Different businesses.<br>Plenty to figure out.</h2><p>My working life started at twelve. These are some of the roles that followed.</p></div><nav class="company-links" aria-label="Jump to a company">${d.rolesData.map(r=>`<a href="#role-${r.id}">${e(r.company)}<small>${e(r.years)}</small></a>`).join('')}</nav><div class="career-list">${d.rolesData.map(role).join('')}</div></section>
<section class="software-section" id="ai"><div class="shell"><div class="section-heading"><span class="eyebrow">Software</span><h2>Another way to<br>get things moving.</h2><p>I started building software because I could see things a business needed and wanted to figure out how to build them.</p><p>I bring the business experience and use AI to help with research, design, coding, and review. I work through what the software needs to do, check the results, and keep improving it. Below, you can see the projects and where each one stands.</p></div><div id="products">${d.aiProjectsData.map(software).join('')}</div><div class="mini-projects">${d.aiMinisData.map(p=>`<article>${img(p.img,p.alt)}<span class="status">${e(p.status)}</span><h3>${e(p.name)}</h3><p>${e(p.text)}</p></article>`).join('')}</div><details class="small-detail" id="process"><summary>How I build</summary><ol class="process-list">${d.aiFlowData.map(f=>`<li><strong>${e(f.name)}</strong><p>${e(f.desc)}</p></li>`).join('')}</ol></details><details class="small-detail" id="ecosystem"><summary>Tools I use, and what each does</summary><div class="tools-grid">${d.aiStoryData.map(s=>`<article><h3>${e(s.title)}</h3><p>${e(s.lead)}</p><ul>${s.tools.map(t=>`<li>${img(t.logo,t.logoAlt||t.name)}<span><strong>${e(t.name)}</strong><small>${e(t.role)}</small></span></li>`).join('')}</ul></article>`).join('')}</div></details></div></section>
<section class="contact-section shell" id="contact"><span class="eyebrow">Let’s talk</span><h2>What are you<br>working through?</h2><p>Let’s talk about your business, what needs to change, and where I could help.</p><a class="contact-email" href="mailto:ngoureau@mac.com">ngoureau@mac.com</a><div class="contact-links"><a href="tel:9175356425">917-535-6425</a><a href="https://www.linkedin.com/in/nicolas-goureau-6ab3237/" target="_blank" rel="noopener">LinkedIn</a></div><details class="reference-request small-detail"><summary>Request references</summary><p>Want to speak with people I’ve worked with? Tell me a little about the opportunity, and I’ll arrange an introduction.</p><form id="reference-form"><label>Your name<input name="name" autocomplete="name" required maxlength="120"></label><label>Company and role<input name="company" autocomplete="organization" required maxlength="180"></label><label>Email<input type="email" name="email" autocomplete="email" required></label><label>The opportunity and what you’d like to discuss<textarea name="story" required maxlength="4000"></textarea></label><button class="button" type="submit">Prepare email request</button><p class="meta" id="reference-status" role="status">Opens your email app. I personally review every request before sharing references.</p></form></details></section>
</main><footer class="shell"><a href="#profile">Nicolas Goureau<span>.</span></a><span>ATLANTA, GA · American, French, Israeli</span><span>© ${new Date().getUTCFullYear()}</span></footer></body></html>`;
fs.writeFileSync('docs/index.html',html.replace(/[ \t]+$/gm,''));
console.log('Built CV: 8 roles, 32 career stories, 23 topics, 7 software projects and 3 additional projects.');
