import fs from 'node:fs';
import {playbook,sourcing,systems,toolkit} from './playbooks.mjs';
import {editorial} from './editorial.mjs';
import {projectStories} from './project-stories.mjs';
import {chapterImages,clientImages} from './career-images.mjs';
const d=JSON.parse(fs.readFileSync('docs/content.json','utf8'));
const e=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const dimensions=JSON.parse(fs.readFileSync('scripts/image-dimensions.json','utf8'));
const img=(src,alt,cls='')=>`<img src="${e(src)}" alt="${e(alt)}" class="${cls}" ${dimensions[src]?`width="${dimensions[src][0]}" height="${dimensions[src][1]}"`:""} loading="lazy" decoding="async">`;
const hist=n=>`history/img-${String(n).padStart(2,'0')}.jpg`;
const photos={moremargin:[4,5,7,8,9],funtown:[13,14,15,16,18],bigbox:[19,21,22,23,24],campingworld:[26,27,28,29,30,31,32,33,35],lemonis:[37,39,40,41,42,43,44,45,46,47,48,49,50,51],courageb:[52,53,54,56,57,58,61]};
const companyPhotos={moremargin:6,funtown:12,bigbox:20,campingworld:34,lemonis:38,courageb:60};
const caps={moremargin:['DJI Fifth Avenue','DJI retail display','DJI store interior','NuvoMed product'],funtown:['Fun Town RV retail','Store and showroom','Product merchandising','Parts and accessories'],bigbox:['FitBox concept rendering','FitBox concept rendering','FitBox exterior concept','FitBox interior concept'],campingworld:['Gander Outdoors','Retail merchandising','Gander Outdoors opening','RV showroom'],lemonis:['W82 · Editorial illustration','Retail concept','W82, Chicago','Retail concept'],courageb:['COURAGE. b fabric sourcing','Boutique interior','Fabric sourcing','Denim & Soul']};
const sentences=text=>text.replaceAll('COURAGE. b','COURAGE§ b').replaceAll('U.S.','U§S§').replaceAll('Mrs.','Mrs§').split(/(?<=[.!?])\s+(?=[A-Z“])/).map(t=>t.replaceAll('§','.'));
const bulletList=text=>`<ul class="career-bullets">${sentences(text).map(t=>`<li>${e(t.trim())}</li>`).join('')}</ul>`;
const flow=(items,label,kind='')=>`<ol class="flowchart ${kind}" aria-label="${e(label)}">${items.map((f,i)=>`<li><span class="flow-number">${String(i+1).padStart(2,'0')}</span><div><h4>${e(f.t||f.name)}</h4><p>${e(f.d||f.desc||'')}</p>${f.output?`<span class="flow-output">Leave with: ${e(f.output)}</span>`:''}${kind==='product-flow'&&i===items.length-1?`<div class="flow-branches"><span>Own website</span><span>Marketplaces</span><span>Wholesale</span><span>Stores</span></div>`:''}</div></li>`).join('')}</ol>`;
const careerTitles={moremargin:'Putting the relationships and experience to work.',funtown:'A store brief became a connected retail business.',bigbox:'An empty big box. A different way to use it.',campingworld:'Four acquired brands. More than 80 stores to reopen.',lemonis:'From an idea on paper to a business with its doors open.',courageb:'A family business, built alongside a full-time career.',sharperimage:'Finding the next product people had not seen before.',kbp:'The client that became my next employer.'};
const careerMedia=(sources,alt)=>`<div class="chapter-media">${sources.map(src=>`<a href="${e(src)}" target="_blank" rel="noopener" aria-label="Open ${e(alt)} image at full size">${img(src,src.startsWith('assets/career/')&&src.endsWith('.webp')?'Editorial illustration — '+alt:alt)}</a>`).join('')}</div>`;
const role=(r,i)=>`<details class="role" id="role-${r.id}" open>
 <summary><span class="role-year">${e(r.years)}</span><span class="role-title"><span class="company-heading"><strong>${e(r.company)}</strong><span class="company-about"><button type="button" class="about-trigger" aria-expanded="false" aria-controls="about-${r.id}">About <span aria-hidden="true">↗</span></button><span class="company-card" id="about-${r.id}" hidden>${img(companyPhotos[r.id]?hist(companyPhotos[r.id]):'assets/about-'+r.id+'.jpg',r.company+' — career archive')}<span class="company-card-copy"><strong>${e(r.company)}</strong><span>${e(r.about)}</span></span></span></span></span><span>${e(r.role)} · ${e(r.location)}</span></span><span class="disclosure" aria-hidden="true"></span></summary>
 <div class="role-body"><p class="role-context">${e(r.context)}</p><h3 class="career-headline">${e(careerTitles[r.id])}</h3><div class="career-tabs" role="tablist" aria-label="${e(r.company)} story sections">${r.chapters.map((c,j)=>`<button type="button" role="tab" id="career-tab-${r.id}-${j}" aria-controls="career-panel-${r.id}-${j}" aria-selected="${j===0}" tabindex="${j===0?0:-1}">${e(c.k)}</button>`).join('')}</div><div class="career-chapters">${r.chapters.map((c,j)=>`<article class="career-chapter" role="tabpanel" id="career-panel-${r.id}-${j}" aria-labelledby="career-tab-${r.id}-${j}" ${j?'hidden':''}>${careerMedia(chapterImages[r.id][j],r.company+' — '+c.k)}<div class="chapter-copy"><h4>${e(c.k)}</h4>${j===0?`<p>${e(c.text)}</p>`:bulletList(c.text)}</div></article>`).join('')}</div>
 ${r.clients?`<div class="client-work"><h4>More of the work</h4><p>${e(r.clientsIntro)}</p><div class="client-stories">${r.clients.map((c,j)=>`<article class="client-story">${careerMedia(clientImages[r.id][j],c.name)}<div><h5>${e(c.name)}</h5><span class="meta">${e(c.kind)}</span>${bulletList(c.did)}</div></article>`).join('')}</div></div>`:''}
 </div></details>`;
const asset=src=>{
 if(fs.existsSync('docs/'+src))return src;
 const name=src.split('/').pop()||'';
 if(/atomiq|ATOMIQ|ChatGPT/i.test(src)){
  if(/mobile/i.test(name))return 'uploads/atomiq-mobile.png';
  if(/sampler/i.test(name))return 'uploads/atomiq-sampler.png';
  if(/sequencer/i.test(name))return 'uploads/atomiq-sequencer.png';
  return 'uploads/atomiq-performance-core.png';
 }
 return null;
};
const software=p=>{
 const shots=(p.shots||[]).map(s=>({...s,src:asset(s.src)})).filter(s=>s.src);
 return `<article class="software-project" id="project-${p.id}"><div class="project-heading"><div><span class="eyebrow">${e(p.role)}</span><h3>${e(p.name)}</h3></div><span class="status">${e(p.status)}</span></div>
 <div class="project-grid"><div class="project-gallery" data-gallery>${shots.length?`<figure><a class="image-link" href="${e(shots[0].src)}" target="_blank" rel="noopener" aria-label="Open ${e(p.name)} screenshot at full size">${img(shots[0].src,shots[0].alt)}</a><figcaption>${e(shots[0].alt)}</figcaption></figure><div class="gallery-controls" role="group" aria-label="${e(p.name)} screenshots">${shots.map((s,i)=>`<button type="button" data-shot="${e(s.src)}" data-alt="${e(s.alt)}" aria-pressed="${i===0}">${e(s.lab)}</button>`).join('')}</div>`:''}</div><div class="project-copy"><span class="eyebrow">The idea behind the work</span><p class="project-opening">${e(projectStories[p.id]?.[0]||p.role)}</p><p>${e(projectStories[p.id]?.[1]||'')}</p><span class="eyebrow">Inside the work</span><ul>${(p.bullets||[]).map(b=>`<li>${e(b)}</li>`).join('')}</ul><details class="small-detail"><summary>How it comes together</summary>${flow(p.flow||[],p.name+' workflow','compact-flow')}${p.domains?`<p>${p.domains.map(e).join(' · ')}</p>`:''}<p class="meta">${e(p.label)}</p></details></div></div></article>`;
};
const journeyDetails=[
 ['What is missing from the range?','Start with the customer and the price tier. Compare the existing offer with the national brand: what would make an owned product worth choosing?','Customer · Assortment · Target price'],
 ['Give the product a clear identity.','Work through the name, logo, colors, typography, packaging, and hangtags as one system. Each brand needs a reason to exist and a recognizable place in the assortment.','Brand · Packaging · Merchandising'],
 ['Write the brief. Work through the samples.','Define materials, specifications, and features before production. Test samples and revise them against the brief; the product needs to earn its place alongside the incumbent.','Specification · Samples · Testing'],
 ['Agree the whole deal.','Use factory relationships to work through cost, tooling, minimum orders, and terms before making a commitment. The product specification and the buying agreement need to describe the same thing.','Factory · Quality · Commercial terms'],
 ['Know the cost of getting it here.','Model landed cost before a unit ships. Freight, customs, compliance, and labeling belong in the plan alongside the factory price.','Freight · Customs · Landed cost'],
 ['Put the stock where it can sell.','Receive and allocate across distribution centers and stores, then plan replenishment. The next step depends on having stock available in the locations that will serve the customer.','Receiving · Allocation · Replenishment'],
 ['One assortment. Four routes to the customer.','Connect the offer across the own website, marketplaces, wholesale, and stores. Watch what sells and bring that information back to the next assortment decision.','Website · Marketplaces · Wholesale · Stores']
];
const journey=()=>`<div class="journey-console"><div class="journey-console-head"><span class="eyebrow">The product journey</span><span>Hover a step · Tap to explore</span></div><div class="journey-layout"><div class="journey-map"><ol class="journey-nodes">${d.plFlowData.map((f,i)=>`<li><button type="button" data-journey="journey-${i}" aria-controls="journey-${i}" aria-expanded="${i===0}"><span class="node-number">${f.n}</span><strong>${e(f.t)}</strong><small>${e(journeyDetails[i][2])}</small><span class="node-open" aria-hidden="true">↗</span></button></li>`).join('')}</ol><div class="journey-channels"><span>Own website</span><span>Marketplaces</span><span>Wholesale</span><span>Stores</span></div><p class="journey-return">↶ Sales and customer feedback return to the assortment decision.</p></div><div class="journey-inspector">${d.plFlowData.map((f,i)=>`<article id="journey-${i}" ${i?'hidden':''}><span class="eyebrow">Step ${f.n} / 07</span><h3>${e(journeyDetails[i][0])}</h3><p>${e(journeyDetails[i][1])}</p><div class="journey-handoff"><span class="eyebrow">What moves forward</span><strong>${e(f.output)}</strong></div><p class="journey-source">${e(f.d)}</p></article>`).join('')}</div></div></div>`;
const pl=d.rolesData.find(r=>r.id==='campingworld');
let html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="ndg-cv-revision" content="20260916-career-sections-v4"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark light"><title>Nicolas Goureau — Retail, Systems & Tools</title><meta name="description" content="Nicolas Goureau. More than 30 years across retail, sourcing, brands, stores, and the P&L. Curious about people, products, and how things work."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;650;700;750;800&family=Source+Sans+3:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="site.css"><script src="site.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="wordmark" href="#profile" aria-label="Nicolas Goureau, introduction">Nicolas Goureau</a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation"><a href="#about">About</a><a href="#opportunity">My next chapter</a><a href="#experience">My journey</a><a href="#build">How I can help</a><a href="#value">What changed</a><a href="#product-journey">Idea to customer</a><a href="#capabilities">Capabilities</a><a href="#ai">Systems & tools</a><a href="#process">Build process</a><a href="#ecosystem">AI toolkit</a><a class="button small" href="#contact">Let’s talk</a></nav></header>
<main id="main">
<section class="hero" id="profile" aria-labelledby="hero-heading"><div class="hero-background" data-parallax="0.38"><img src="illustrations/43.webp" alt="" fetchpriority="high"></div><div class="hero-shade"></div><div class="hero-content"><p class="eyebrow">Nicolas Goureau · ATLANTA, GA</p><h1 id="hero-heading">I see possibilities.<br><span>I like figuring out</span><br>how to get there.</h1><p class="hero-lead">Give me a business problem and I’m curious—about the product, the numbers, and the people who know the business.</p><a href="#experience" class="text-link">Follow my journey <span aria-hidden="true">↓</span></a><p class="availability">Open to remote or hybrid work<br>Willing to travel</p></div><div class="portrait-wrap" data-parallax="0.14"><img src="assets/img-00-tight.png" alt="Nicolas Goureau" class="portrait" fetchpriority="high"></div></section>
<section class="about-section" id="about"><div class="about-copy"><span class="eyebrow">The person behind the work</span><h2>Curious about people.<br>Always figuring something out.</h2><p>I started working at twelve in my mother’s clothing store, steaming, folding, and tagging merchandise. Other jobs followed through high school and college. Retail was part of my life long before it became my career.</p><p>I grew up across three cultures and hold three passports: American, French, and Israeli. I’m based in Atlanta now, and my working life has taken me through New York, San Francisco, Chicago, Miami, and Fort Worth. Decades of travel across Europe, Asia, and South America have brought relationships, different perspectives, and a lot of questions I would never have thought to ask at home.</p><p>I like people. I bring energy to a conversation, enjoy getting to know how someone thinks, and am comfortable moving between a factory floor, a boardroom, and a market stall. I like finding things—a supplier, a product, a deal, or an answer buried in the numbers. If I don’t understand something, I tend to stay with it until I do.</p><p>For a decade, I founded and ran a fashion company with my sister alongside full-time executive roles, working nights and weekends. That same curiosity now takes me into systems and tools built with AI: finding practical ways to save time, connect information, and help people get on with their work.</p><p>Outside work, I cook, make art, and enjoy time with family and friends. Golf and pickleball bring out my competitive side. Exploring and researching satisfy the curious side. And there is usually something to fix: I never hire a handyman because I enjoy figuring out what’s wrong, learning how it works, and getting it working again.</p><div class="personal-notes"><div><strong>Languages</strong><p><span class="language-row"><span>English</span><span>Fluent</span></span><span class="language-row"><span>French</span><span>Fluent</span></span><span class="language-row"><span>Hebrew</span><span>Conversational</span></span><span class="language-row"><span>Spanish</span><span>Basic</span></span></p></div><div><strong>Places & connections</strong><p>Atlanta, GA · Based here<br>New York · San Francisco · Chicago<br>Miami · Fort Worth<br>Networks across Europe, Asia, and South America</p></div><div><strong>Outside work</strong><p>Family and friends · Cooking · Art<br>Golf · Pickleball<br>Exploring · Researching · Fixing things</p></div><div><strong>Location & availability</strong><p>Open to remote or hybrid work.<br>Willing to travel.</p></div></div></div></section>
<section class="opportunity-section" id="opportunity"><div class="shell"><span class="eyebrow">What I’m looking for</span><h2>A business to help move forward.<br>A team to do it with.</h2><p class="intro-large">I’m looking for senior operating responsibility inside a company or investment group, working with its people to turn opportunity into a stronger business.</p><p>My experience fits customer-facing retail, consumer and service businesses where product, sourcing, brands, stores and the P&amp;L need to work together. I’m interested in the full investment lifecycle: understanding a business before acquisition, integrating it after close, improving the operation, planning growth and preparing it for its next chapter.</p><p>I want to work alongside a CEO, founder or investment team: show what is possible, agree where the organization should go, and help its people get there. The systems and tools I build are part of how I make that work move faster.</p><div class="availability-line"><span>Atlanta, GA</span><span>Remote or hybrid</span><span>Willing to travel</span></div></div></section>
<section class="introduction shell" aria-label="How I work"><span class="eyebrow">A question is a good place to start.</span><div><p class="intro-large">I ask questions, connect the pieces, and find ways forward.</p><p>I enjoy showing people what could work and working alongside them to make it happen. I bring 30+ years across retail, sourcing, brands, stores, and the P&amp;L. I also build systems and tools that help people work faster, reduce avoidable steps, and make better use of their time. Sometimes that means software; sometimes it means connecting the information and tools a team already has.</p></div></section>
<section class="experience-section shell" id="experience"><div class="section-heading"><span class="eyebrow">Where I’ve worked</span><h2>I started on<br>the shop floor.</h2><p>At twelve, I was steaming, folding, and tagging clothes in my mother’s store. Other jobs followed through school and college. The work below grew from that beginning: learning the product, understanding the customer, and figuring out what it takes to run the business.</p><p>Advertising led me to The Sharper Image, first as a client and then as my employer. My sister and I later started COURAGE. b, which I ran alongside full-time executive roles. The work expanded into acquisitions, national store rollouts, sourcing, and the systems that connect it all.</p></div><div class="career-route" aria-label="Career progression"><span class="eyebrow">Follow the work · most recent first</span><nav aria-label="Jump to a company">${d.rolesData.map(r=>`<a href="#role-${r.id}"><small>${e(r.years)}</small><strong>${e(r.company)}</strong><span>${e(careerTitles[r.id])}</span></a>`).join('')}</nav><p class="meta">COURAGE. b ran alongside my executive roles; these dates overlap.</p></div><div class="career-list">${d.rolesData.map(role).join('')}</div></section>
<section class="work-section light" id="build"><div class="shell"><div class="section-heading"><span class="eyebrow">What that experience brings to your business</span><h2>Where my experience<br>meets your business.</h2><p>If you are working through a product range, a store rollout, an acquisition, or a team slowed down by disconnected systems, these are the connections I bring. A product decision affects sourcing, pricing, stock, and the shop floor. I have worked across those responsibilities, and I work through them with the people who know your business.</p></div><div class="work-grid">${d.tracksData.map((t,i)=>`<article><span class="index">0${i+1}</span><h3>${e(t.name)}</h3><p>${e(t.how)}</p><details class="small-detail"><summary>Examples from the work</summary><ul class="proof-list">${t.proof.map(p=>`<li><strong>${e(p.num)}</strong><span>${e(p.what)}<small>${e(p.where)}</small></span></li>`).join('')}</ul></details></article>`).join('')}</div>
<section class="capabilities-section" id="capabilities"><div class="section-heading"><span class="eyebrow">Capabilities</span><h3>What I bring to the table.</h3><p>Hover, focus, or tap a capability to see how I approach it.</p></div>${d.compGroupsData.map((g,gi)=>`<div class="capability-group"><h4>${e(g.label)}</h4><div class="capability-buttons">${g.items.map((item,ii)=>`<button type="button" class="capability-button" data-capability="cap-${gi}-${ii}" aria-controls="cap-${gi}-${ii}" aria-expanded="false">${e(item.name)}</button>`).join('')}</div></div>`).join('')}<div class="capability-explanations">${d.compGroupsData.map((g,gi)=>g.items.map((item,ii)=>`<article id="cap-${gi}-${ii}" class="capability-panel" hidden><h4>${e(item.name)}</h4><p>${e(item.story)}</p></article>`).join('')).join('')}</div></section></div></section>
<section class="results-section shell" id="value"><div class="section-heading"><span class="eyebrow">Results</span><h2>The decisions mattered.<br>Here’s what changed.</h2></div><div class="results-grid">${d.highlightsData.map((h,i)=>`<a class="result-row" href="#role-${['moremargin','bigbox','campingworld','campingworld','lemonis','courageb','funtown','campingworld'][i]}"><span class="result-number">${e(h.num)}<small>${e(h.unit)}</small></span><span class="result-copy">${e(h.desc)}<span class="result-source">${e(['More Margin Co.','Big Box Group','Camping World','Camping World','Marcus Lemonis LLC','COURAGE. b','Fun Town RV','Camping World'][i])} <span aria-hidden="true">↗</span></span></span></a>`).join('')}</div></section>
<section class="brand-story" id="product-journey"><div class="brand-intro shell"><div><span class="eyebrow">A closer look · Private label</span><h2>From a gap on the shelf<br>to a product in hand.</h2><p>Each brand started with a question about the assortment: what was missing, and could we offer something better? The answer had to work all the way from product and packaging through sourcing, delivery, and the sale.</p></div><figure>${img('assets/cwpl-nepallo-rack.png','Nepallo fishing apparel collection')}<figcaption>Nepallo · Fishing and sun protection</figcaption></figure></div><div class="product-strip shell">${d.plWallData.map(p=>`<figure>${img(p.src,p.name+' — '+p.cat)}<figcaption><strong>${e(p.name)}</strong>${e(p.cat)}</figcaption></figure>`).join('')}</div><div class="shell"><details class="small-detail private-label" open><summary>Follow the product from idea to sale</summary>${playbook(sourcing,'source','From idea to sale — my sourcing playbook')}<p class="flow-loop">↺ Watch what sells, listen to customers, and bring that learning back to the next product decision.</p>${pl.plStory.map(s=>`<article><h3>${e(s.t)}</h3><p>${e(s.d)}</p><div class="product-detail-images">${s.imgs.map(i=>img(i.src,i.alt)).join('')}</div><p class="meta">${e(s.brands)}</p></article>`).join('')}<div class="client-grid">${pl.plCats.map(c=>`<article><h4>${e(c.t)}</h4><p>${e(c.d)}</p><p class="meta">Benchmarked against ${e(c.vs)}</p></article>`).join('')}</div></details></div></section>
<section class="software-section" id="ai"><div class="shell"><div class="section-heading"><span class="eyebrow">The same curiosity. A new set of tools.</span><h2>Less time chasing.<br>More time doing.</h2><p>The retail work kept bringing me back to the same questions: where is the information, why are we entering it again, and what is holding up the next person? At Fun Town RV, that grew into product databases, ordering, replenishment, and sales channels. Today I also use AI to build systems and tools around those kinds of problems.</p><p>It starts with the business and the people doing the work. I use AI to research, design, build, and check possible answers. Software is one part of that; the point is a useful tool the organization can actually use.</p></div><details class="small-detail process-section" id="process" open><summary>How a business problem becomes a working tool</summary><p>This is the playbook I use to turn an operating problem into a useful system. Each step connects the work to the people who will use it and the organization that needs the result.</p>${playbook(systems,'systems','From business problem to working system')}<p class="flow-loop">↺ Use it, learn from the team, and feed the next problem back into the process.</p></details><details class="small-detail" id="ecosystem" open><summary>The AI toolkit — who does what</summary><p>I give each tool a job. The sequence below shows where it fits, from the first question to the information people use every day.</p>${toolkit(d.aiStoryData,img)}</details><div class="section-heading project-intro"><span class="eyebrow">Examples</span><h3>The problems that became projects.</h3><p>Each project begins with something I wanted to make easier, clearer or more useful. These examples show how that question becomes a working approach. The stage shown is identified for each project.</p></div><div id="products">${d.aiProjectsData.map(software).join('')}</div><div class="mini-projects">${d.aiMinisData.map(p=>`<article>${img(p.img,p.alt)}<span class="status">${e(p.status)}</span><h3>${e(p.name)}</h3><p>${e(p.text)}</p></article>`).join('')}</div></div></section>
<section class="contact-section shell" id="contact"><span class="eyebrow">Let’s talk</span><h2>What’s the next chapter?</h2><p>Tell me where the business is today and what you want to change. A new range, a difficult integration, stores that need attention, or work that takes longer than it should. We can talk through where my experience would be useful and the people I would be working alongside.</p><a class="contact-email" href="mailto:ngoureau@mac.com">ngoureau@mac.com</a><div class="contact-links"><a href="tel:9175356425">917-535-6425</a><a href="https://www.linkedin.com/in/nicolas-goureau-6ab3237/" target="_blank" rel="noopener">LinkedIn</a></div><details class="reference-request small-detail"><summary>Request references</summary><p>Want to speak with people I’ve worked with? Tell me a little about the opportunity, and I’ll arrange an introduction.</p><form id="reference-form"><label>Your name<input name="name" autocomplete="name" required maxlength="120"></label><label>Company and role<input name="company" autocomplete="organization" required maxlength="180"></label><label>Email<input type="email" name="email" autocomplete="email" required></label><label>The opportunity and what you’d like to discuss<textarea name="story" required maxlength="4000"></textarea></label><button class="button" type="submit">Prepare email request</button><p class="meta" id="reference-status" role="status">Opens your email app. I personally review every request before sharing references.</p></form></details></section>
</main><footer class="shell"><a href="#profile">Nicolas Goureau</a><span>ATLANTA, GA · Open to remote or hybrid work</span><span>© ${new Date().getUTCFullYear()}</span></footer></body></html>`;
html=editorial(html,d,e,img);
html=html.replace(/<figcaption>[\s\S]*?<\/figcaption>/g,'');
fs.writeFileSync('docs/index.html',html.replace(/[ \t]+$/gm,''));
console.log('Built CV: 8 roles, 32 career stories, 23 topics, 7 software projects and 3 additional projects.');
