const groups = [
['Retail & Operations','retail-operations','A concept sketch of store layout, fixtures, merchandise and inventory.',[
['Retail Operations','I connect the customer-facing business with the work that keeps it running.', ['I look at assortment, staffing, replenishment and systems together: a change in one affects the others.','I turn plans into clear responsibilities and usable routines, giving people room to think like owners.','At Fun Town, my work connected stores, purchasing, inventory and operating systems.']],
['Multi-Unit Strategy','I look for what should be consistent across locations—and where local judgment matters.', ['I build common ways of working around buying, information and execution so teams do not have to solve the same problem repeatedly.','I consider the people, stock and support each location needs before adding complexity.','My Fun Town experience connected multiple retail locations with shared purchasing and systems.']],
['Operational Turnaround','I start with the operating problem behind the disappointing result.', ['I examine product economics, inventory, workflow and customer experience to find practical points of improvement.','I sequence changes around available resources and work with the people closest to the problem.','Across the Marcus businesses, I contributed to specific operating and integration assignments; my role was hands-on execution.']],
['Space Management','I treat space as part of the operating model, not simply a visual statement.', ['I connect product placement and customer movement with capacity, replenishment and the work of the team.','I translate a concept into practical fixture and merchandising decisions with the relevant specialists.','The W82 store work brought together the store concept, product presentation and implementation.']],
['Inventory Control','I want inventory decisions to reflect what the business can sell, support and afford.', ['I connect assortment, purchasing and stock information so decisions account for both availability and cash tied up in goods.','I make the information and handoffs useful to the people buying, receiving and selling the product.','At Fun Town, inventory and retail systems were part of the same operating effort.']]
]],
['Product & Sourcing','product-sourcing','A concept sketch of product samples, material swatches, measurement and packaging development.',[
['Sourcing','I build supplier relationships around a clear commercial need and a workable product brief.', ['I consider quality, landed cost, lead times and consistency together, rather than treating the lowest quote as the answer.','I communicate requirements clearly and work through samples and practical constraints with suppliers.','At Fun Town, my KAMPTIME and USA Rec. Supply work connected direct sourcing with private-label products and the needs of the selling business.']],
['Private Label','I connect the product opportunity with the economics and work needed to put it on sale.', ['I bring together the customer need, supplier brief, packaging, pricing and route to market from the beginning.','I look at the complete offer—not just factory cost—so sourcing decisions support a viable selling proposition.','At Fun Town, KAMPTIME and USA Rec. Supply were the two house brands in our direct-sourcing program.']],
['Product Development','I translate an idea into a brief that suppliers and specialists can work with.', ['I clarify the intended customer, useful features, price position and practical constraints before refining the product.','I coordinate samples, packaging and feedback, while leaving specialist engineering and manufacturing work with the people responsible for it.','The Sharper Image cooling-neck-band work connected a product opportunity with packaging and commercial presentation.']],
['Brand Development','I look for a clear reason for a brand to exist—and consistency in how it reaches the customer.', ['I connect positioning with assortment, presentation and the actual customer experience.','I adapt useful ideas from other categories, testing whether they fit the business rather than copying the surface treatment.','My Denim & Soul work brought brand and retail considerations into the same operating conversation.']],
['Assortment Strategy','I build an assortment around a customer and a business purpose.', ['I consider how products work together across price points, use cases and margin, rather than judging each item in isolation.','I connect selection with supplier options, presentation and inventory implications.','Through More Margin, I have worked on product and sourcing decisions with their commercial fit in mind.']]
]],
['Commercial & Growth','commercial-growth','A concept sketch of commercial planning, a calculator, product samples and shipping documents.',[
['Margin Improvement','I look for margin in the decisions that create the offer, not only in the final selling price.', ['I connect sourcing, product mix, private label, packaging and pricing to understand where economics can improve.','I weigh potential gains against quality, working capital and the resources needed to execute.','At Fun Town, selected product and private-label work demonstrated how sourcing and assortment choices could change product economics.']],
['Pricing Strategy','I consider what a customer will value alongside what the business needs to earn.', ['I assess the offer, competitive context and product economics together, rather than applying a markup without context.','I consider how price points work across the assortment and what they imply for sourcing and inventory.','My More Margin work links product selection and sourcing with the commercial proposition.']],
['Vendor Negotiation','I negotiate the relationship around the needs of the whole business.', ['I look beyond unit price to terms, delivery, support and the responsibilities on both sides.','I use a clear brief and an understanding of each party’s needs to build a workable agreement.','At Sharper Image, my catalog co-op work involved supplier participation and commercial support for the catalog.']],
['E-Commerce','I connect the online storefront with the operation that must deliver the order.', ['I consider product information, merchandising, inventory and fulfillment together when developing a channel.','I work through platform choices and practical handoffs with the team and specialists responsible for implementation.','My Fun Town work included e-commerce alongside retail operations and systems.']],
['Acquisition Integration','I help translate a change in ownership or business structure into practical operating work.', ['I learn how the existing business works before changing its processes, preserving useful knowledge and relationships.','I connect people, products, information and responsibilities so the combined operation can move forward.','My Marcus work included practical integration contributions involving Camping World and Denim & Soul; transaction leadership was outside that role.']],
['Portfolio Optimization','I help owners see where operating attention and shared resources can be useful across businesses.', ['I compare needs, dependencies and priorities so several teams can make progress with the resources available.','I look for useful connections in suppliers, knowledge and systems while respecting what makes each business different.','My work across the Marcus businesses supports this operating perspective; owners retain investment and transaction decisions.']]
]],
['Tools & AI','tools-ai','A concept sketch of connected software panels, information flows and automation.',[
['AI Research & Analysis','I use AI to broaden research and organize information around a real business question.', ['I start with the decision to be made, then use tools to compare options, organize material and surface questions worth investigating.','I check important claims against sources and keep judgment with the person responsible for the decision.','My own building projects demonstrate this working method; they are distinct from client deployments.']],
['AI Integrated Tools','I connect a useful business task with tools that can help perform it.', ['I define the workflow, required information and desired output before choosing how AI should support the work.','I build and refine with AI assistance, checking behavior and identifying where human review is needed.','My own software projects provide examples of this approach; their maturity and development methods are covered in the later toolkit section.']],
['Workflow Automation','I look for repeated work that can become a reliable process.', ['I map the inputs, rules, exceptions and handoffs before deciding what to automate.','I connect tools and information where practical, keeping responsibility and checks visible to the people using the process.','My operating systems experience at Fun Town informs this approach; newer AI-assisted automations are part of my own project work.']],
['Content Development','I turn a business idea into material that helps people understand and act on it.', ['I clarify the audience, message and purpose before developing copy, visuals or a presentation.','I bring commercial context to the work and collaborate with creative specialists where their skills are needed.','At KBP, I contributed to pitch and presentation work, including the Priceline trophy story preserved in my career section.']],
['Shopify & POS Development','I approach selling systems through the work of the customer and the team.', ['I connect product data, merchandising, checkout and inventory needs when shaping a storefront or POS workflow.','I coordinate configuration and implementation with the people responsible, then check the handoffs that make the system useful.','My Fun Town experience included e-commerce and retail systems; it grounds my approach to platforms such as Shopify and POS tools.']],
['Databases & Reporting','I want better information to change an operating decision.', ['I start with the questions a team needs to answer and organize the underlying data around them.','I connect reporting with usable definitions, consistent inputs and the person who will act on the result.','At Fun Town, my systems work connected inventory and operating information; my own newer projects extend that thinking into dashboards and tools.']],
['Adobe, Canva & Office','I use practical tools to make commercial work clearer and easier to carry forward.', ['I choose the format that serves the task: a financial model, supplier brief, presentation, product document or visual explanation.','I develop working materials myself and bring in specialists when the work calls for deeper design or technical expertise.','My career examples include product and catalog presentation, pitch materials and operating plans.']]
]]
];
export function capabilities(e) {
return `<section class="capabilities-section" id="capabilities"><div class="section-heading"><span class="eyebrow">The connections behind my work</span><h3>What I’m made of.</h3></div><div class="cap-map">${groups.map(([label,asset,alt,items],gi)=>`<div class="cap-cluster cap-cluster-${gi}"><h4>${e(label)}</h4><a class="cap-art" href="illustrations/section14-${asset}.webp" target="_blank" rel="noopener" title="Illustrative concept sketch — view full size"><img src="illustrations/section14-${asset}.webp" alt="${e(alt)} Illustrative concept, not a completed project." width="1200" height="800" loading="lazy"></a><div class="cap-pills">${items.map(([name],ii)=>`<button type="button" class="cap-pill" data-capability="cap-${gi}-${ii}" aria-controls="cap-${gi}-${ii}" aria-expanded="false">${e(name)}</button>`).join('')}</div></div>`).join('')}<div class="cap-center"><div class="cap-invitation"><p>Explore what I bring.</p><span>Hover or tap a capability.</span></div><div class="cap-detail" hidden><button type="button" class="cap-close" aria-label="Close capability details">Close</button>${groups.map((g,gi)=>g[3].map(([name,intro,bullets],ii)=>`<article id="cap-${gi}-${ii}" class="cap-detail-panel" aria-labelledby="cap-title-${gi}-${ii}" hidden><h4 id="cap-title-${gi}-${ii}">${e(name)}</h4><p>${e(intro)}</p><ul>${bullets.map(b=>`<li>${e(b)}</li>`).join('')}</ul></article>`).join('')).join('')}</div></div></div></section>`;
}
