import fs from 'node:fs';
import assert from 'node:assert/strict';
import {actions,connectPage} from './connect.mjs';
const packageJson=JSON.parse(fs.readFileSync('package.json','utf8'));
assert.equal(packageJson.dependencies.jose,'6.2.12','JWT verifier is pinned to the vetted jose package');
assert.equal(packageJson.devDependencies.wrangler,'4.147.0','Local Worker tooling uses the current official Wrangler release');
const productionWorkerConfig=fs.readFileSync('wrangler.jsonc','utf8');
assert(/"keep_vars"\s*:\s*true\b/.test(productionWorkerConfig),'Production Wrangler config preserves existing runtime variables for Cloudflare Builds deploys');
const previewWorkerConfig=fs.readFileSync('wrangler.preview.jsonc','utf8');
assert(previewWorkerConfig.includes('"main": "worker/index.js"'),'Preview deploy runs the HUD access gate instead of static-only assets');
assert(previewWorkerConfig.includes('"run_worker_first": true'),'Preview HUD requests reach the Worker access gate before assets');
assert(previewWorkerConfig.includes('"compatibility_date": "2026-09-28"'),'Preview uses the production compatibility date');
const deployWorkflow=fs.readFileSync('.github/workflows/pages.yml','utf8');
assert(deployWorkflow.includes("- 'worker/**'"),'Production workflow runs when Worker protection changes');
assert(deployWorkflow.includes('npx wrangler deploy --name ndgcv --keep-vars'),'Production workflow deploys the root Worker that contains the HUD gate');
for(const page of ['index.html','connect.html']) {
 const h=fs.readFileSync('dist/'+page,'utf8');
 const ids=[...h.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 assert.equal(new Set(ids).size,ids.length,`${page}: duplicate IDs`);
 for(const m of h.matchAll(/href="#([^"]+)"/g))assert(ids.includes(m[1]),`${page}: missing anchor ${m[1]}`);
 for(const m of h.matchAll(/(?:src|href|data-shot)="([^"]+)"/g)){
  let file=m[1].replaceAll('&amp;','&');
  if(/^(?:[a-z]+:|#|\/\/)/i.test(file))continue;
  file=file.split(/[?#]/)[0].replace(/^\//,'');
  if(!file)file='index.html';if(file==='connect')file='connect.html';
  assert(fs.existsSync('dist/'+file),`${page}: missing asset ${file}`);
 }
 assert(!/class="(?:software-project|build-feature|build-portfolio)"|href="#project-|id="products"/.test(h),'Portfolio leaked into public page');
}
const h=fs.readFileSync('dist/index.html','utf8');
assert.equal((h.match(/class="role career-designed /g)||[]).length,8);
assert.equal((h.match(/role="tabpanel"/g)||[]).length,32);
assert.equal((h.match(/class="client-story"/g)||[]).length,12);
assert.equal((h.match(/class="build-group"/g)||[]).length,6);
assert(h.includes('id="education-heading">Education</h2>'));
assert(h.includes('section-19-aup-plaque.webp'));
assert(h.includes('I started working at twelve'));
assert(h.includes('assets/img-00-tight.png'));
const c=fs.readFileSync('dist/connect.html','utf8');
assert.equal((c.match(/class="illustrated-action /g)||[]).length,6);
assert(!c.includes('qr-'),'No QR on QR destination');
assert.equal(actions.find(a=>a.id==='references').href,'mailto:ngoureau@mac.com?subject=Reference%20request');
assert.equal(actions.find(a=>a.id==='linkedin').href,'https://www.linkedin.com/in/nicolas-goureau-6ab3237/');
assert(c.includes('download="Nicolas-Goureau.vcf"'));
const v=fs.readFileSync('dist/nicolas-goureau.vcf','utf8');
assert(v.startsWith('BEGIN:VCARD\r\nVERSION:3.0\r\n'));assert(v.endsWith('END:VCARD\r\n'));
assert(v.includes('EMAIL;TYPE=INTERNET:ngoureau@mac.com\r\n'));assert(v.includes('TEL;TYPE=VOICE:+19175356425\r\n'));
const extended=connectPage([...actions,...['one','two','three'].map(id=>({id,label:'Future action '+id,href:'/',hint:'Test extension'}))]);
assert.equal((extended.match(/class="illustrated-action /g)||[]).length,9,'Action registry must extend without fixed coordinates');
const data=JSON.parse(fs.readFileSync('archive/the-agency/portfolio-data.json'));
assert.equal(data.aiProjectsData.length,7);assert.equal(data.aiMinisData.length,3);
for(const file of JSON.parse(fs.readFileSync('archive/the-agency/asset-manifest.json')))assert(fs.existsSync('archive/the-agency/assets/'+file));
assert(!fs.existsSync('dist/archive'));assert(!fs.existsSync('dist/content.json'));
console.log('Passed: packaged assets and anchors; 8 roles / 32 panels / 12 company examples; 6 build stages; Education; 6 contact actions; reference subject; LinkedIn target; vCard; extendable 9-action markup; portfolio archive. Visual responsive checks remain separate.');

assert(v.includes('item1.URL:https://www.linkedin.com/in/nicolas-goureau-6ab3237/\r\n'));
assert(!h.includes('More ways to connect'));

assert(h.includes('id="career-master"'));
assert(!/<details class="role career-designed [^>]+\sopen/.test(h));
assert.equal((h.match(/<article class="systems-group"/g)||[]).length,6);
assert.equal((h.match(/<article class="build-group"/g)||[]).length,6);
assert(h.includes('id="contact-heading">Let’s connect</h2>'));
assert(!c.includes('class="connect-footer"'));
assert.equal(actions.find(a=>a.id==='download').href,'/Nicolas_Goureau_Executive_CV.pdf');
assert(fs.readFileSync('dist/Nicolas_Goureau_Executive_CV.pdf').subarray(0,4).toString()==='%PDF');
assert(!h.includes('6 checkout lanes established'));
assert(!h.match(/<footer[\s\S]*?<\/footer>/)?.[0].includes('remote'));
const homepageNav=h.match(/<nav id="navigation"[\s\S]*?<\/nav>/)?.[0]||'';
assert(homepageNav.includes('class="private-workspace-link"'),"Homepage navigation includes the private workspace entry");
assert(homepageNav.includes('href="/hud/"'),"Private workspace entry targets the packaged HUD route");
assert(homepageNav.includes('aria-label="Open private workspace"'),"Private workspace entry has an accessible name");
assert(homepageNav.includes('href="/media/"'),"Homepage navigation includes the Media destination");
const privateWorkspaceLink=homepageNav.match(/<a class="private-workspace-link"[\s\S]*?<\/a>/)?.[0]||'';
assert(privateWorkspaceLink.includes('data-tooltip="Private workspace"'),"Private workspace entry exposes a hover and focus tooltip");
assert(privateWorkspaceLink.includes('<svg '),"Private workspace entry uses an icon, not visible link text");
assert(privateWorkspaceLink.includes('M3 8.5h6l2-2h3l2 2h5v10.5H3z'),"Private workspace entry uses the unboxed folder glyph");
assert(!privateWorkspaceLink.includes('M5 5h14v14H5z'),"Private workspace entry no longer uses the boxed glyph");
assert(!/>Private workspace</.test(privateWorkspaceLink),"Private workspace entry remains visually discreet");
assert(homepageNav.includes('class="sidebar-primary-links"'),"Homepage navigation separates core CV links from lower navigation");
assert(homepageNav.includes('class="sidebar-apps-group"'),"Homepage navigation has a lower Apps, Media and Products group");
assert(homepageNav.includes('<a href="/apps/">Apps</a>'),"Lower Apps group retains its working destination");
assert(homepageNav.includes('<a href="/media/">Media</a>'),"Lower Media group retains its working destination");
assert(homepageNav.includes('<a href="/products/">Products</a>'),"Products has a working destination");
assert(!homepageNav.includes('Explore more'),"Homepage navigation has no extra group heading");
assert(!homepageNav.includes('Coming soon'),"Homepage navigation has no availability badges");
assert(!homepageNav.includes('sidebar-future-link'),"Homepage navigation has no disabled future link");
const visualCorrections=fs.readFileSync('scripts/visual-corrections.css','utf8');
assert(visualCorrections.includes('.sidebar-apps-group{'),"Sidebar styles include the lower group");
assert(visualCorrections.includes('bottom:112px'),"Desktop Scout clears the bottom utility controls");
assert(visualCorrections.includes('bottom:64px;width:180px;border-top'),"Desktop utility controls have one subtle divider above them");
assert(visualCorrections.includes('.site-header #navigation .sidebar-primary-links{min-height:0;overflow-y:auto'),"Desktop primary links scroll independently from the lower group");
assert(visualCorrections.includes('.sidebar-utilities .private-workspace-link,.site-header #navigation .sidebar-utilities .section-all-controls'),"Desktop utilities share the same icon row");
assert(visualCorrections.includes('width:44px;min-width:44px;height:44px;min-height:44px'),"Desktop utility icons retain an accessible hit area");
assert(visualCorrections.includes('.private-workspace-link svg{width:20px;height:20px;stroke-width:1.6}'),"Desktop utility glyphs share the same visual scale");
assert.equal((visualCorrections.match(/\.sidebar-utilities \.private-workspace-link svg\{width:20px;height:20px;stroke-width:1\.6\}/g)||[]).length,2,"Utility glyphs stay matched at desktop and mobile breakpoints");
assert(visualCorrections.includes(':focus-visible{outline:2px solid #f4e0c2'),"Desktop utility icons retain a visible keyboard focus state");
console.log('Document edits: collapsed career master and roles, combined approaches/stages, PDF download, contact cleanup and footer checked.');

assert.equal((h.match(/class="illustrated-action /g)||[]).length,6,"Homepage and connect share all six actions");
assert.equal((h.match(/<img[^>]* src="assets\/idea-to-sale\/[^" ]+-private-label.png"/g)||[]).length,9,"All nine distinct private-label groups are published");


const appsPage=fs.readFileSync('docs/apps/index.html','utf8');
for(const [label,page] of Object.entries({homepage:h,apps:appsPage})){
 assert(page.includes('site.css?v=nav-mobile-refresh-20261007'),`${label} requests the refreshed shared stylesheet`);
 assert(page.includes('site.js?v=nav-mobile-refresh-20261007'),`${label} requests the refreshed shared navigation script`);
 assert(!page.includes('nav-final-corrections-20261007')&&!page.includes('layout-20260925'),`${label} has no stale navigation asset URL`);
}
assert(appsPage.includes('class="apps-page"'),"Apps page uses the CV-continuation shell");
assert(appsPage.includes('<span class="eyebrow">Apps</span>'),"Apps eyebrow is present");
assert(appsPage.includes('Practical tools built around real work.'),"Apps portfolio headline is present");
assert(appsPage.includes('/assets/build-process/section-18-background.webp'),"Apps parallax background is present");
assert(appsPage.includes('class="scout-widget"'),"Scout is present on the Apps page");
assert.equal((appsPage.match(/class="app-card"/g)||[]).length,9,"All nine apps are published as cards");
assert(appsPage.includes('Deal Closer Pro'));
assert(appsPage.includes('data-video-open="deal-closer-video"'),"Deal Closer Pro card has a video action");
assert(appsPage.includes('/apps/assets/deal-closer-pro-demo.mp4'),"Deal Closer Pro video is embedded");
assert(fs.existsSync('dist/apps/assets/deal-closer-pro-demo.mp4'),"Deal Closer Pro video is packaged");
assert(appsPage.includes('ImportFlow'));
assert(appsPage.includes('VendorReady'));
assert(appsPage.includes('WarrantyDesk'));
for(const name of ['RestoreFlow','FactoryQ','FranchiseOps','RentalOps','PermitPath'])assert(appsPage.includes(name));
for(const slug of ['restoreflow','factoryq','franchiseops','rentalops','permitpath']){
 assert(appsPage.includes(`/apps/${slug}/`),`${slug} demo route is listed`);
 assert(fs.existsSync(`dist/apps/assets/${slug}/preview-desktop.webp`),`${slug} desktop preview is packaged`);
 assert(fs.existsSync(`docs/apps/assets/${slug}/preview-mobile.webp`),`${slug} mobile QA preview is retained`);
}
assert.equal((appsPage.match(/No account required/g)||[]).length,9,"All nine cards disclose no-account demo access");
assert(!appsPage.includes('<footer'),"Apps page has no footer");
const appsNav=appsPage.match(/<nav id="navigation"[\s\S]*?<\/nav>/)?.[0]||'';
assert(appsNav.lastIndexOf('>Apps<') > appsNav.lastIndexOf('>Let’s connect<'),"Apps is the final navigation item");
assert(appsNav.includes('class="sidebar-apps-group"'),"Apps page keeps the lower group");
assert(appsNav.includes('href="/media/"'),"Apps navigation links to the Media destination");
assert(appsNav.includes('href="/products/"'),"Apps navigation links to the Products destination");
assert(!appsNav.includes('Explore more')&&!appsNav.includes('Coming soon')&&!appsNav.includes('sidebar-future-link'),"Apps navigation has no heading, availability badge or disabled product link");
assert(appsNav.includes('class="private-workspace-link"'),"Apps page retains the private workspace action");
assert(appsNav.includes('aria-label="Open private workspace"'),"Apps private workspace action has an accessible name");
console.log('Apps page: nine demo cards, screenshots, routes, parallax shell, Scout, no footer and Apps/Media/Products navigation checked.');

const mediaPage=fs.readFileSync('docs/media/index.html','utf8');
for(const [label,page] of Object.entries({media:mediaPage,products:fs.readFileSync('docs/products/index.html','utf8')})){
 assert(page.includes('site.css?v=nav-mobile-refresh-20261007')&&page.includes('site.js?v=nav-mobile-refresh-20261007'),`${label} requests refreshed shared navigation assets`);
 assert(!page.includes('nav-final-corrections-20261007')&&!page.includes('layout-20260925'),`${label} has no stale shared navigation asset URL`);
}
assert(mediaPage.includes('class="holding-page media-page"'),"Media page uses the established site shell");
assert(mediaPage.includes('Exciting things are coming. Check back soon.'),"Media page has the agreed single message");
assert(mediaPage.includes('class="holding-support">A new chapter is taking shape.</p>'),"Media page adds its restrained supporting line");
assert(mediaPage.includes('class="holding-signature">Nicolas</p>'),"Media page includes Nicolas's restrained signature");
assert(mediaPage.includes('data-page-collapsible'),"Media page supports the shared minimize control");
assert(!mediaPage.includes('A place for the work in motion.')&&!mediaPage.includes('This collection is in development')&&!mediaPage.includes('Coming soon'),"Media page has no verbose roadmap copy or availability badge");
assert(mediaPage.includes('/illustrations/build-v3.webp'),"Media page uses an existing local brand image");
assert(mediaPage.includes('/holding-page.css?v=holding-mobile-refresh-20261007'),"Media page uses the cache-refreshed holding-page treatment");
assert(mediaPage.includes('href="/apps/"'),"Media page retains the Apps destination");
const mediaNav=mediaPage.match(/<nav id="navigation"[\s\S]*?<\/nav>/)?.[0]||'';
assert(mediaNav.includes('class="sidebar-primary-links"'),"Media page separates primary navigation");
assert(mediaNav.includes('class="sidebar-apps-group"'),"Media page includes the lower group");
assert(mediaNav.includes('href="/media/" aria-current="page"'),"Media is marked as the current destination");
assert(mediaNav.includes('href="/products/"'),"Media navigation links to the Products destination");
assert(!mediaNav.includes('Explore more')&&!mediaNav.includes('Coming soon')&&!mediaNav.includes('sidebar-future-link'),"Media navigation has no heading, availability badge or disabled product link");
assert(mediaNav.includes('class="private-workspace-link"'),"Media page retains the private workspace action");
assert(fs.existsSync('dist/media/index.html'),"Media page is packaged");
assert(fs.existsSync('dist/illustrations/build-v3.webp'),"Media page background image is packaged");
const productsPage=fs.readFileSync('docs/products/index.html','utf8');
assert(productsPage.includes('class="holding-page products-page"'),"Products page uses the established site shell");
assert(productsPage.includes('Exciting things are coming. Check back soon.'),"Products page has the agreed single message");
assert(productsPage.includes('class="holding-support">A new chapter is taking shape.</p>'),"Products page adds its restrained supporting line");
assert(productsPage.includes('class="holding-signature">Nicolas</p>'),"Products page includes Nicolas's restrained signature");
assert(productsPage.includes('data-page-collapsible'),"Products page supports the shared minimize control");
assert(productsPage.includes('/illustrations/product-v3.webp'),"Products page uses an existing local brand image");
assert(productsPage.includes('/holding-page.css?v=holding-mobile-refresh-20261007'),"Products page uses the cache-refreshed holding-page treatment");
const productsNav=productsPage.match(/<nav id="navigation"[\s\S]*?<\/nav>/)?.[0]||'';
assert(productsNav.includes('href="/products/" aria-current="page"'),"Products is marked as the current destination");
assert(productsNav.includes('href="/apps/"')&&productsNav.includes('href="/media/"'),"Products navigation retains Apps and Media destinations");
assert(!productsNav.includes('Explore more')&&!productsNav.includes('Coming soon')&&!productsNav.includes('sidebar-future-link'),"Products navigation has no heading, availability badge or disabled product link");
assert(fs.existsSync('dist/products/index.html'),"Products page is packaged");
assert(fs.existsSync('dist/illustrations/product-v3.webp'),"Products page background image is packaged");
assert(fs.existsSync('dist/holding-page.css'),"Shared holding-page stylesheet is packaged");
assert(fs.readFileSync('docs/site.js','utf8').includes('sidebarUtilities||nav'),"Homepage keeps mobile utility controls with the private workspace action");
assert(fs.readFileSync('docs/site.js','utf8').includes('(sidebarUtilities||nav).prepend(allControls)'),"Minimize is placed before the private workspace utility");
assert(fs.readFileSync('docs/scout.js','utf8').includes('scout-pause-glyph'),"Scout uses a drawn control glyph instead of an emoji tile");
assert(!visualCorrections.includes('body:has(#navigation.is-open) .scout-widget{visibility:hidden}'),"Scout remains visible when the mobile navigation is open");
for(const [label,page] of Object.entries({homepage:h,apps:appsPage,media:mediaPage,products:productsPage}))assert(page.includes('/scout.css?v=scout-visible-20261007'),`${label} requests the mobile-visible Scout stylesheet`);
assert(visualCorrections.includes('.site-header #navigation .sidebar-utilities{display:flex;align-items:center;gap:8px'),"Mobile utility controls stay in one row");
assert(visualCorrections.includes('.site-header .menu-toggle{border-color:#eabb87;color:#eabb87'),"Mobile menu toggle uses the gold navigation accent");
console.log('Media and Products: branded image, one agreed message, packaged routes, and shared navigation checked.');

const hud=fs.readFileSync('dist/hud/index.html','utf8');
const hudCSS=fs.readFileSync('dist/hud/hud.css','utf8');
const hudJS=fs.readFileSync('dist/hud/hud.js','utf8');
assert(hud.includes('data-hud-preview="sample-only"'),"Career HUD is explicitly sample-only");
assert(hud.includes('<h1 id="workspace-title">Today</h1>'),"Career HUD includes the concise Today view");
assert(hud.includes('Opportunities'),"Career HUD includes career navigation");
assert(hud.includes('Contacts &amp; references'),"Career HUD includes relationship navigation");
assert(hud.includes('Sample data'),"Career HUD visibly labels its sample state");
assert(hud.includes('id="connections-list"'),"Career HUD includes a private connection setup region");
assert(hud.includes('data-hud-opportunities-endpoint="/api/hud/opportunities"'),"Career HUD declares its protected opportunities endpoint");
assert(hud.includes('data-hud-references-endpoint="/api/hud/references"'),"Career HUD declares only its fixed protected references endpoint");
assert(hud.includes('data-hud-photo-endpoint="/api/hud/photo"'),"Career HUD declares only its fixed protected photo endpoint");
assert(hud.includes('data-hud-connections-endpoint="/api/hud/connections"'),"Career HUD declares only its fixed protected connections endpoint");
assert(hud.includes('id="hud-runtime-status"'),"Career HUD includes the lower-rail connection status box");
assert(hud.includes('Connection status'),"Career HUD labels the lower-rail connection status box");
assert(hud.includes('id="hud-menu-toggle"')&&hud.includes('id="hud-mobile-menu"'),"Career HUD uses the public-site style mobile Menu control and drawer");
assert(hud.includes('id="hud-location"')&&hud.includes('id="hud-current-time"')&&hud.includes('id="hud-weather"'),"Career HUD includes location, time, and weather header states");
assert(hud.includes('private-photo-slot'),"Career HUD reserves a protected photo slot without packaging private photo pixels");
assert(hud.includes('id="hud-private-photo-a"')&&hud.includes('id="hud-private-photo-b"'),"Career HUD has two private in-memory image layers for a crossfade");
assert(fs.existsSync('dist/hud/hud.css'),"Career HUD stylesheet is packaged");
assert(fs.existsSync('dist/hud/hud.js'),"Career HUD script is packaged");
assert(hudJS.includes('Private setup support is not available.'),"Career HUD honestly labels unavailable connection setup");
assert(fs.existsSync('dist/hud/assets/storefront.webp'),"Career HUD retail photo remains under the protected HUD route");
assert(hudCSS.includes('prefers-reduced-motion'),"Career HUD honors reduced motion");
assert(hudCSS.includes('.hud-mobile-menu.is-open { display: block; }'),"Career HUD opens a bounded mobile navigation drawer instead of clipping a horizontal nav");
assert(hudJS.includes('runOnce'),"Career HUD protects duplicate actions");
assert(hudJS.includes('setHudMenu')&&hudJS.includes('renderWeekStrip'),"Career HUD controls its mobile menu and derives the sample week from the current date");
assert(hudJS.includes("fetch(endpoint, { credentials: 'same-origin'"),"Career HUD requests only its protected same-origin runtime endpoint");
assert(hudJS.includes("headers: { Accept: 'image/jpeg' }"),"Career HUD requests only JPEG bytes from the protected photo stream");
assert(hudJS.includes("cache: 'no-store'"),"Career HUD does not cache protected photo requests");
assert(hudJS.includes("redirect: 'error'"),"Career HUD rejects a protected photo redirect rather than following another source");
assert(hudJS.includes('const PHOTO_ROTATION_MS = 20_000'),"Career HUD refreshes its protected photo stream every twenty seconds");
assert(!hudJS.includes('drive.google.com'),"Career HUD contains no Drive photo URL or client-selected source");
assert(hudJS.includes('trustedCareerSheetUrl'),"Career HUD validates the runtime-only opportunities-sheet link");
assert(hudJS.includes('normalizeLiveReferences')&&hudJS.includes('referenceConnection'),"Career HUD replaces sample contact cards only after a valid protected references response");
assert(hudJS.includes('REFERENCE_PERMISSION_VALUES')&&hudJS.includes('Ask first'),"Career HUD renders only the approved reference permission vocabulary");
assert(hudJS.includes('trustedReferenceEmail')&&hudJS.includes('trustedLinkedInUrl'),"Career HUD validates private contact links before rendering them");
assert(!hudJS.includes('api/hud/references?'),"Career HUD does not construct a caller-selected references query");
assert(hudJS.includes("method: 'PATCH'")&&hudJS.includes('expectedRevision')&&hudJS.includes('actionId'),"Career HUD saves only the revision-guarded live opportunity contract");
assert(hudJS.includes('data-live-opportunity-form')&&hudJS.includes('Save changes'),"Career HUD exposes a bounded live status and next-action save control");
assert(hudJS.includes('refreshAfterLiveSaveIssue'),"Career HUD refreshes after a live conflict or ambiguous save instead of claiming a clean failure");
assert(hudJS.includes('navigator.geolocation.getCurrentPosition'),"Career HUD requests device location only from the explicit header action");
assert(hud.includes('Weather unavailable'),"Career HUD does not invent weather data without a provider");
assert(!hud.includes('https://drive.google.com/'),"Career HUD does not package a Drive URL");
assert(!hud.includes('https://docs.google.com/spreadsheets/'),"Career HUD does not package an opportunities-sheet URL");
assert(!hud.includes('spreadsheets.google.com'),"Career HUD does not package a Sheet URL");
console.log('Career HUD: packaged /hud/ preview, protected runtime contract, no public Drive or Sheet URL, reduced motion, and local-only sample state checks passed.');
