// Shared, build-time action registry. Add an item here; layout does not need coordinates.
export const actions = [
  {id:'email', label:'Email me', href:'mailto:ngoureau@mac.com', hint:'Tell me what you’re working toward.'},
  {id:'contact', label:'Save my contact', href:'/nicolas-goureau.vcf', hint:'Download my contact card to your address book.', download:true},
  {id:'references', label:'Request reference', href:'mailto:ngoureau@mac.com?subject=Reference%20request', hint:'Ask me for a personal introduction.'},
  {id:'linkedin', image:'linkedin-v2', label:'LinkedIn', href:'https://www.linkedin.com/in/nicolas-goureau-6ab3237/', hint:'See my professional profile on LinkedIn.', external:true},
  {id:'download', image:'download-cv', extension:'png', label:'Download CV', href:'/Nicolas-Goureau-CV.pdf', hint:'Download my two-page CV as a PDF.', download:'Nicolas-Goureau-CV.pdf'},
  {id:'cv', image:'cv-v2', label:'View my Interactive CV', href:'/', hint:'Explore my experience and the work behind it.'},
];
const e = s => String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
export function actionLink(a,context='connect') {
  return `<a class="illustrated-action action-${a.id}" href="${e(a.href)}" aria-describedby="${context}-hint-${a.id}"${a.external?' target="_blank" rel="noopener noreferrer"':''}${a.download?` download="${typeof a.download==='string'?a.download:'Nicolas-Goureau.vcf'}"`:''}><span class="action-art"><img src="/assets/connect/${a.image||a.id}.${a.extension||'webp'}" alt="" width="480" height="480" decoding="async"></span><span class="action-label">${e(a.label)}</span><span class="action-hint" id="${context}-hint-${a.id}" role="tooltip">${e(a.hint)}</span></a>`;
}
export function contactSection() {
  return `<section class="contact-section shell" id="contact" aria-labelledby="contact-heading"><span class="eyebrow">Start a conversation</span><h2 id="contact-heading">Let’s connect</h2><p>I’d welcome a conversation about what you’re working toward and where I could help.</p><ul class="contact-reasons"><li><strong>Build a business:</strong> turn an opportunity into a working operation.</li><li><strong>Develop new offerings:</strong> connect customer needs with commercial goals.</li><li><strong>Improve operations:</strong> simplify workflows and make execution easier.</li><li><strong>Build business solutions:</strong> connect data, teams and everyday decisions.</li><li><strong>Create programs and apps:</strong> turn business needs into practical tools.</li></ul><nav class="contact-actions" aria-label="Get in touch">${actions.map(a=>actionLink(a,'section20')).join('')}</nav></section>`;
}
export function connectPage(items=actions) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Connect — Nicolas Goureau</title><meta name="description" content="Explore Nicolas Goureau’s work, get in touch, request references or save his contact details."><link rel="canonical" href="https://nicolasgoureau.com/connect"><link rel="stylesheet" href="/connect.css"><script src="/connect.js" defer></script></head>
<body class="connect-page"><a class="connect-skip" href="#connect-actions">Skip to contact options</a><div class="connect-scene" aria-hidden="true"></div><header class="connect-header"><a class="connect-home" href="/" aria-label="Nicolas Goureau — Interactive CV">Nicolas Goureau<span>Business Building &amp; Operations</span></a><a class="back-to-cv" href="/">View my Interactive CV <span aria-hidden="true">↗</span></a></header><main class="connect-main"><div class="connect-intro"><p class="connect-eyebrow">Connect</p><h1>Good things start with a conversation.</h1><p>Explore my work, get in touch, or save my details for later.</p></div><div class="connect-hub"><div class="connect-identity"><img class="connect-portrait" src="/assets/img-00-tight.png" alt="Nicolas Goureau" width="627" height="845" fetchpriority="high"><h2>Nicolas Goureau</h2></div><nav class="connect-orbit" id="connect-actions" aria-label="Contact options">${items.map(a=>actionLink(a)).join('')}</nav></div></main></body></html>`;
}
