export function education(){return `<section id="education" class="education-section" aria-labelledby="education-heading">
<div class="education-backdrop" data-parallax="0.12" aria-hidden="true"></div>
<div class="education-content"><header class="section-heading"><span class="eyebrow">Where business and creativity meet.</span><h2 id="education-heading">The foundations behind the work.</h2></header>
<article class="education-school" aria-labelledby="education-miami"><header><h3 id="education-miami">University of Miami <span>· 2006</span></h3><p class="education-credentials">B.S.C. Advertising<br>B.B.A. in Economics<br>B.A. in Theatre Arts</p></header><div class="education-pair"><ul>
<li><strong>Advertising:</strong> I learned to connect an audience, an offering and a persuasive message. That foundation informs how I position products, shape customer experiences and give creative work a clear commercial purpose.</li>
<li><strong>Economics:</strong> I developed a framework for understanding markets, incentives and resource allocation. It supports the way I weigh pricing, costs and competing priorities—and examine the tradeoffs behind a business decision.</li>
<li><strong>Theatre arts:</strong> My studies spanned stage design, production, box office operations and some acting. Seeing the workings behind a performance helped me connect creative ambition with the people, preparation and practical coordination needed to deliver it.</li>
</ul><img src="assets/education/section-19-miami-logo.webp" width="1536" height="1024" loading="lazy" alt="Sketch adaptation of the University of Miami Ring Theatre entrance, with circular architectural details, ivy and palms; institutional context, with an added university logo." title="Adapted from a university-hosted Ring Theatre photograph; institutional context, with an added university logo."></div></article>
<article class="education-school" aria-labelledby="education-paris"><header><h3 id="education-paris">The American University of Paris <span>· Summer 2002</span></h3><p class="education-credentials">Accelerated summer business management program</p></header><div class="education-pair"><ul>
<li>Before Miami, I completed an accelerated summer program that gave me an early foundation in entrepreneurship, marketing and project execution.</li>
<li>Living in Paris made international experience part of that education. Studying business in another cultural setting broadened my perspective on customers, communication and the context in which an organization operates.</li>
</ul><img src="assets/education/section-19-aup-logo.webp" width="1536" height="1024" loading="lazy" alt="Sketch adaptation of AUP’s historic entrance at 31 avenue Bosquet, with its stone arch, wooden doors and iron balcony; based on a 1973 archival photograph, with the current AUP logo added for identification." title="Adapted from AUP’s 1973 archive photograph of Bosquet, a campus building in use during 2002."></div></article></div></section>`;}
