const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
export const sourcing=[
['Find the commercial opportunity','I start with the customer, the assortment and the economics. A product needs a reason to exist before it needs a supplier.','Compare the current range, customer needs, price tiers and national-brand benchmarks. Separate a genuine gap from another variation of something we already sell. Establish the target selling price and the margin the business needs.','Merchandising and finance agree the customer, target price, initial volume and margin objective.','The organization puts development time and working capital behind a defined opportunity, with a shared test for whether the idea is worth pursuing.'],
['Give the brand a job','The brand should help a customer understand why this product belongs in their life and why it belongs in our assortment.','Define the position and price tier, then develop the name, visual identity, packaging, hangtags and usage standards together. Make the differentiation visible at shelf distance and understandable on a small product page.','A brand brief, identity standards and packaging direction that design, buying and marketing can all use.','The company owns a recognizable proposition. Teams present one coherent offer across categories and channels instead of creating disconnected products.'],
['Turn the brief into a tested product','I translate the commercial brief into specifications a factory can make and a buyer can judge.','Write down materials, dimensions, features and packaging requirements. Review samples against the brief and the benchmark product. Record revisions, test the next sample and resolve differences before approving production.','An agreed specification and approved sample. If the sample fails the brief, it returns for revision before the order moves forward.','Buying, quality and the supplier work from the same definition of acceptable. Catching a problem on the sample table is much less disruptive than discovering it after arrival.'],
['Choose the factory and settle the terms','My supplier relationships help open the conversation; the quality and commercial requirements determine the agreement.','Compare capability, cost, minimum quantities, tooling, lead times and payment terms. Work through trade-offs with the buying team. Keep the agreed sample, specification and order terms connected so that a lower quote does not quietly become a different product.','A supplier agreement with clear product standards, quantities, costs, timing and responsibilities.','The organization can make an informed commitment. It understands the cash requirement and delivery assumptions before placing the order.'],
['Plan the landed cost and arrival','A factory price is only one part of what the business will pay. I work through the route to our receiving dock before the product ships.','Bring freight, customs, labeling and applicable compliance requirements into the plan. Connect shipment timing with launch timing and receiving capacity. Revisit the selling economics using landed cost, rather than leaving those costs for someone else to discover later.','A landed-cost model, shipment plan and receiving requirements shared with finance and operations.','Finance sees the real economics, operations can prepare, and the launch plan reflects when stock can actually become available.'],
['Make the inventory useful','The handoff from a shipment to saleable stock needs as much attention as the initial product idea.','Set up product records, receiving, allocation and replenishment across the distribution center and store fleet. Match the initial allocation to the selling plan, then use demand to adjust where stock goes. Make ownership of exceptions clear.','Accurate item records, available inventory and an allocation and replenishment plan the team can run.','The right teams can find and sell the stock. This reduces avoidable handoffs and helps keep capital from sitting in the wrong location.'],
['Launch, listen and improve','I connect the product to four routes to the customer: our own website, marketplaces, wholesale and stores.','Align product information, pricing, packaging and presentation across channels. Give selling teams the information they need. Review sales, margin, availability and customer feedback together, then feed what we learn into the next buy or product revision.','A coordinated offer, a performance review and a decision to replenish, revise or retire the product.','The business gains an owned assortment it can keep improving. The sale becomes information for the next decision, closing the loop from customer need to customer response.']
];
export const systems=[
['Start with the work','I begin with the people doing the job, where time disappears and what the business needs to change.','Walk through the current task from request to completion. Identify duplicate entry, missing information, recurring exceptions and approvals. Agree what a useful improvement would look like before choosing technology.','A defined problem, an owner and a practical measure of success.','The organization invests in a real operating need and gives the people affected a voice in the solution.'],
['Research before building','I look for the shortest sound route to a useful result.','Review existing systems, available integrations and reusable components. Compare buying, connecting and building against the team’s requirements. Check the evidence and constraints with another perspective before settling the direction.','A reuse, integrate or build decision with the reasoning recorded.','The team avoids rebuilding capabilities it already has and focuses effort where the business needs something different.'],
['Write the operating brief','The brief describes how the business should work, not just what a screen should look like.','Define users, tasks, inputs, outputs, permissions, exceptions and acceptance checks. Separate the first useful release from later additions. Use plain language so operators can challenge the logic before implementation starts.','A shared brief and acceptance criteria.','Business owners and builders can judge the same outcome, reducing ambiguity and expensive rework.'],
['Map information and decisions','I map the handoffs before asking anyone or any AI to implement them.','Show where information originates, which system owns it and where it moves next. Identify who can approve changes and what happens when information is missing or a connection fails. Design the workflow around the organization’s responsibilities.','A system map, ownership rules and a sequence of small implementation steps.','The organization gets connected work with clear accountability instead of another isolated application.'],
['Assign clear jobs','I use different AI tools for research, design, implementation and review, with defined boundaries.','Give each task a clear brief, relevant context and a deliverable. Split independent work into separate lanes while keeping shared standards and human decisions explicit. Compare outputs and resolve disagreements before integration.','Defined tasks and reviewable handoffs.','Work can move faster while responsibility stays visible. The organization can inspect how a result was reached.'],
['Keep a durable record','Decisions and working files need to survive the conversation that created them.','Store code, briefs, decisions and handoffs in the shared project record. Use version control to track changes and preserve a known working state. Make the next person’s starting point clear.','A versioned source of truth and a usable handoff.','Knowledge stays with the organization, and future improvements do not depend on reconstructing old chats.'],
['Build a useful slice','I connect one real piece of work end to end, then expand from what the team can use.','Build the smallest meaningful workflow, connect its data and check it with users. Resolve the first practical problems before adding more screens or automation. Keep each change small enough to inspect and revise.','A working version of a real task.','The team sees value early and can correct the direction while changes are still manageable.'],
['Test the business logic','A screen that looks right still has to handle the work correctly.','Check calculations, permissions, handoffs, missing data and failure paths. Compare the result with the agreed brief. Have the people who know the work examine whether the behavior makes sense.','Evidence against the acceptance criteria and a list of unresolved issues.','The organization can distinguish a promising demonstration from a tool ready for operating use.'],
['Review and release','I keep consequential decisions under human review.','Review the release against the brief, confirm ownership and explain how to use it. Check the deployed version and prepare a way to recover if a change causes a problem. Resolve required approvals before the tool takes consequential action.','A reviewed release and an operating handoff.','The business can adopt the tool with clearer expectations and responsibility for its use.'],
['Improve with the team','The first release is the start of learning from actual use.','Collect user feedback, inspect recurring problems and compare the workflow with the original objective. Prioritize changes that remove meaningful friction. Carry lessons and reusable patterns into the next problem.','A prioritized improvement list and a better next version.','The company gains a repeatable way to improve how it works, rather than a one-off piece of software.']
];
export function playbook(items,id,label){return `<div class="playbook" aria-label="${label}"><div class="playbook-heading"><p class="eyebrow">My operating playbook</p><p>Follow the steps. Hover, focus or tap a step for its purpose; open it for the full working method.</p></div><ol class="playbook-steps">${items.map((s,i)=>`<li><details class="playbook-step" ${i===0?'open':''}><summary><span class="step-number">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(s[0])}</strong><span class="step-preview">${esc(s[1])}</span></span><span class="step-plus" aria-hidden="true">+</span></summary><div class="step-body">${id==='source'&&[0,5].includes(i)?`<img class="step-evidence" src="history/img-${i===0?'03':'01'}.jpg" alt="${i===0?'Existing retail assortment and packaging':'Warehouse inventory awaiting allocation'}" loading="lazy">`:''}<p>${esc(s[1])}</p><div class="step-columns"><div><h4>How I work through it</h4><p>${esc(s[2])}</p><h4>The handoff</h4><p>${esc(s[3])}</p></div><aside><h4>What the organization gains</h4><p>${esc(s[4])}</p></aside></div></div></details></li>`).join('')}</ol><div class="playbook-return">↶ ${id==='source'?'Sales, margin and customer feedback inform the next assortment decision.':'What the team learns becomes the starting point for the next improvement.'}</div></div>`}
export const toolReasons={
'ChatGPT':'I use ChatGPT to turn a business conversation into a structured brief, connect research findings and review the proposed approach. It helps the team move from a broad question to a decision it can inspect.',
'Claude':'I use Claude as another reasoning partner to work through complex requirements and challenge assumptions. Comparing perspectives helps me catch gaps before they become implementation work.',
'Grok':'I use Grok for independent research and a second view of an idea. It helps widen the evidence and pressure-test the direction before the business commits.',
'Perplexity':'I use Perplexity to discover sources and investigate existing solutions. It helps ground the brief in evidence that can be checked.',
'Gemini':'I use Gemini for another research and analytical perspective. It gives me an additional way to examine material and compare conclusions.',
'Claude Design':'I use Claude Design to explore interfaces and interactive prototypes. The team can react to how a workflow feels before committing to the finished build.',
'Canva':'I use Canva to turn working ideas into clear visual communication and presentations. It helps people understand the direction and give useful feedback.',
'Claude Code':'I use Claude Code to implement defined work in the repository and help test it. Clear tasks and versioned changes make the build easier to inspect.',
'Codex':'I use Codex to build, debug and review systems against the operating brief. It helps translate a practical requirement into a working, testable change.',
'Grok Build':'I use Grok Build for rapid application prototypes and independent implementation work. It makes an idea concrete enough for the team to evaluate.',
'Open Claw':'I use Open Claw for agent operations within a defined workflow. Its place is to coordinate delegated work while keeping task boundaries visible.',
'Apps Script':'I use Apps Script to connect tasks in Google Workspace. It removes repetitive copying between spreadsheets, files and routine business workflows.',
'GitHub':'I use GitHub to preserve source code, decisions and handoffs. The company keeps a durable record that another person can pick up.',
'GitHub Actions':'I use GitHub Actions for repeatable checks and build workflows. It reduces the manual steps between a reviewed change and a consistent release.',
'Nano Banana Pro':'I use Nano Banana Pro to explore and create visual concepts. It helps communicate a proposed direction before commissioning finished material.',
'Seedream':'I use Seedream as another image-generation option when exploring visual directions. Comparing outputs helps me choose a treatment suited to the message.',
'Seedance':'I use Seedance to explore motion and video concepts. It helps show an idea over time when a still image is not enough.',
'Magnific':'I use Magnific to enhance selected imagery where extra detail improves the final presentation. It is a finishing step after the image direction is chosen.',
'Topaz Gigapixel':'I use Topaz Gigapixel to improve image resolution for larger layouts. It helps prepare available assets for a clearer presentation.',
'Google Sheets':'I use Google Sheets for structured operating data and controls that people can inspect and update. It keeps the business involved in the workflow.',
'Google Drive':'I use Google Drive for organized source material, assets and handoffs. It gives collaborators a shared place to find the current work.',
'Domo':'I use Domo to bring operating information into dashboards. It helps teams see the measures they need for day-to-day decisions.',
'Power BI':'I use Power BI to analyze business data and communicate performance. It helps turn records into questions and actions the organization can work through.'};
export function toolkit(groups,img){let used=new Set();return `<div class="toolkit-groups">${groups.map(g=>{const ts=g.tools.filter(t=>{if(used.has(t.name))return false;used.add(t.name);return true});return `<div class="toolkit-group"><h3>${esc(g.title)}</h3><p>${esc(g.lead)}</p><div class="toolkit-items">${ts.map((t,i)=>`<div class="tool-item"><button type="button" class="tool-trigger" aria-expanded="false" aria-controls="tool-${[...used].indexOf(t.name)}">${img(t.logo,t.logoAlt||t.name)}<span>${esc(t.name)}</span><span aria-hidden="true">+</span></button><div class="tool-tooltip" id="tool-${[...used].indexOf(t.name)}" hidden><strong>Why I use ${esc(t.name)}</strong><p>${esc(toolReasons[t.name]||t.role)}</p></div></div>`).join('')}</div></div>`}).join('')}</div>`}
