// Loopback-only harness. Not bundled into the production Worker.
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';
import {handle} from './worker.mjs';import {fingerprint} from './sheets.mjs';
const file=process.env.CV_PREVIEW_DATA||'/tmp/cv-command-preview.json';
let state;try{state=JSON.parse(await fs.readFile(file,'utf8'))}catch{state={records:[],events:[]}}
const store={mode:'local preview',writeEnabled:true,list:async()=>structuredClone(state.records),history:async id=>state.events.filter(e=>e.recordId===id).reverse(),save:async(record,previous,actor)=>{const now=new Date().toISOString();record={...record,version:await fingerprint(record.data),createdAt:previous?.createdAt??now,updatedAt:now};state.records=state.records.filter(r=>r.id!==record.id);state.records.unshift(record);state.events.push({recordId:record.id,created_at:now,actor,summary:previous?'Updated record':'Created record'});await fs.writeFile(file,JSON.stringify(state),{mode:0o600});return record}};
const workspace={id:'preview',name:'Local preview',email:'preview@example.invalid'};
const assets={fetch:async request=>{let p=new URL(request.url).pathname;if(p==='/')p='/index.html';if(!['/index.html','/style.css','/app.js','/model.mjs','/schema.mjs'].includes(p))return new Response('Not found',{status:404});const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.mjs':'text/javascript'};return new Response(await fs.readFile(path.join('public',p)),{headers:{'Content-Type':types[path.extname(p)]}})}};
const server=http.createServer(async(req,res)=>{try{const host=req.headers.host;if(host!==`127.0.0.1:${server.address().port}`){res.writeHead(403);res.end();return}const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>196608){res.writeHead(413);res.end();return}chunks.push(c)}const request=new Request(`http://${host}${req.url}`,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const result=await handle(request,{ASSETS:assets},async()=>workspace,()=>store);res.writeHead(result.status,Object.fromEntries(result.headers));res.end(Buffer.from(await result.arrayBuffer()))}catch{res.writeHead(500);res.end('Preview error')}});
server.listen(Number(process.env.PORT||4177),'127.0.0.1',()=>console.log(`Local preview http://127.0.0.1:${server.address().port}`));
